repos:
    - repo: local
      hooks:
          - id: ruff
            name: ruff check
            entry: make lint-all
            language: system
            types: [python]
            pass_filenames: false
            always_run: true

          - id: mypy
            name: mypy strict check
            entry: make typing-all
            language: system
            types: [python]
            pass_filenames: false
            always_run: true

          - id: unittest-coverage
            name: run unittests with coverage
            entry: make coverage
            language: system
            types: [python]
            pass_filenames: false
            always_run: true

          - id: e2e
            name: run e2e tests
            entry: make e2e
            language: system
            types: [python]
            pass_filenames: false
            always_run: true

          - id: commitizen
            name: commitizen check
            entry: make check-commit-msg
            language: system
            pass_filenames: true
            stages: [commit-msg]
